ex05/LifeProTips/config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resource :vote, module: :posts
  end

  get 'users/sign_in' => 'users#sign_in', as: :sign_in

  post 'users' => 'users#create'

  get '/login' => 'sessions#new', as: :login

  post '/login' => 'sessions#create'

  delete 'users/logout' => 'sessions#destroy', as: :logout

  namespace :admin do
    resources :users, except: %i[new create]
    resources :votes, only: :index
    resources :posts do
      resource :vote, only: [:create, :destroy]
    end
  end

  resources :users, only: %i[edit update]

  get '/home' => 'users#home', as: :home
  root 'posts#index'

end

ex05/LifeProTips/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :votes, through: :posts
  validates :name, presence: true, uniqueness: true, on: :create
  validates :email, presence: true, uniqueness: true, on: :create
  validates :password, length: { minimum: 8 }, on: :create
  before_save { self.email = email.downcase }
  before_save { self.name = name.downcase }
end

ex05/LifeProTips/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: %i[edit update]

  def index
    @users = User.all
  end

  def home
    cookies[:animal] =
      {
        value: get_random_animal,
        expires: Time.current + 1.minute
      }
  end

  def new
    @user = User.new
  end

  def edit; end

  def update
    user_params[:email].downcase!
    user_params[:name].downcase!
    if @user.update_attributes(user_params)
      redirect_to root_path
    else
      render :edit
    end
    # render nothing: true
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # If user saves in the db successfully:
      flash[:notice] = 'Compte créé avec succès'
      session[:user_id] = @user.id.to_s
      redirect_to root_path, notice: 'vous êtes connecté !'
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = 'Oups, création impossible...'
      render 'sign_in'
    end
  end

  def sign_in
    @user = User.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def get_user
    @user = User.find(params[:id])
    unless admin?
      # redirect_to root_path if current_user != @user
    end
  end
end

ex05/LifeProTips/app/views/users/edit.html.erb
<h1>
  Modifier votre nom ou email
</h1>
<%= form_for @user do |f| %>

  <div class="field">
    <%= f.label :Nom %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </div>

  <div class="action">
    <%= f.submit :Modification %>
  </div>
<% end %>

ex05/LifeProTips/app/views/users/home.html.erb
<h1>
  Home sweet home
</h1>
<div>

</div>
<% if current_user %>
  <div>
    Welcome <%= current_user.name.capitalize %> |
    <% if admin? %>
      <%= link_to 'Administrate_users', admin_users_path %>
    <% else %>
      <div>
        Pour changer votre nom ou email <%= link_to 'Modifier nom ou email', edit_user_path(current_user) %>
      </div>
    <% end %>
    <%= link_to :Log_out, logout_path, method: :delete %>
  </div>

<% else %>
  <div>
    Welcome <%= "#{cookies[:animal]}_visitor" %> | <%= link_to :Sign_in, sign_in_path %> <%= link_to :Login, login_path %>
  </div>
<% end %>
<br/>

<%= debug(params) if Rails.env.development? %>

ex05/LifeProTips/app/views/users/sign_in.html.erb
<h1>Engagez-vous, vous verrez du pays !</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">    
      <div class="alert alert-danger">
              The form contains <%= pluralize(@user.errors.count, "error") %>.     
      </div>
          
      <ul>    
        <% @user.errors.full_messages.each do |msg| %>      
          <li><%= msg %></li>    
        <% end %>    
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nom %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %><br/>
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="action">
    <%= f.submit :Inscription %>
  </div>
<% end %>
<%= link_to 'revenir à l\'accueil', home_path %>