ex05/LifeProTips/config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resource :vote, module: :posts
  end

  get 'users/sign_in' => 'users#sign_in', as: :sign_in

  post 'users' => 'users#create'

  get '/login' => 'sessions#new', as: :login

  post '/login' => 'sessions#create'

  delete 'users/logout' => 'sessions#destroy', as: :logout

  namespace :admin do
    resources :users, except: %i[new create]
    resources :votes, only: :index
    resources :posts do
      resource :vote, only: [:create, :destroy]
    end
  end

  resources :users, only: %i[edit update]

  get '/home' => 'users#home', as: :home
  root 'posts#index'

end

ex05/LifeProTips/app/models/vote.rb
class Vote < ActiveRecord::Base
  # belongs_to :votant, class_name: :user
  belongs_to :user
  belongs_to :post
end

ex05/LifeProTips/app/controllers/admin/votes_controller.rb
class Admin::VotesController < ApplicationController
  before_action :set_post, only: :create
  before_action :authenticate_user

  def create
    vote = @post.votes.where(user_id: current_user.id).first_or_create
    # value = vote.value + params[:value].to_i
    vote.update_attributes(value: params[:value])
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Post has a vote' }
      format.json { render :show, status: :ok, location: @post }
    end
  end

  def index
    @posts = Post.order(created_at: :desc, title: :asc, user_id: :asc)
  end

  def destroy
    vote = Vote.find(params[:vote])
    vote.delete
    redirect_to admin_votes_path, alert: 'Vote destroyed'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

ex05/LifeProTips/app/controllers/posts/votes_controller.rb
class Posts::VotesController < ApplicationController
  before_action :set_post
  before_action :authenticate_user

  def create
    vote = @post.votes.where(user_id: current_user.id).first_or_create
    # value = vote.value + params[:value].to_i
    vote.update_attributes(value: params[:value])
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Post has a vote' }
      format.json { render :show, status: :ok, location: @post }
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

ex05/LifeProTips/app/views/admin/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Votants Names</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td>
        <ul>
          <% post.votes.each do |vote| %>
            <li><%= votant_name(vote.user_id) %>
              <a><%= button_to 'Destroy Vote', admin_post_vote_path(post), method: :delete, params: {vote: vote, value: 0} %></a>
            </li>
          <% end %>
        </ul>
      </td>
      <td><%= link_to 'Show', admin_post_path(post) %></td>
      <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
      <td><%= link_to 'Destroy', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>